# Generated by Django 6.0.5 on 2026-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_add_player_to_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='player_color',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
