# Generated by Django 5.2.14 on 2026-05-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameresult_player_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco', models.CharField(help_text='ECO code, e.g. B20', max_length=10)),
                ('name', models.CharField(help_text='Opening name', max_length=255)),
                ('moves', models.TextField(help_text="SAN move sequence, e.g. '1. e4 c5'")),
                ('fen', models.TextField(db_index=True, help_text='3-field FEN (board side castling)', unique=True)),
                ('move_count', models.PositiveIntegerField(default=0, help_text='Number of half-moves to reach this position')),
            ],
            options={
                'ordering': ['eco', 'move_count'],
                'indexes': [models.Index(fields=['eco'], name='idx_opening_eco')],
            },
        ),
    ]
