# Generated by Django 6.0.6 on 2026-06-15 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Replace '0001_initial' with whatever your last migration is
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_theme', models.CharField(
                    choices=[('classic', 'Classic'), ('green', 'Green'), ('blue', 'Blue'), ('midnight', 'Midnight')],
                    default='classic',
                    max_length=20,
                )),
                ('piece_set', models.CharField(
                    choices=[('classic', 'Classic'), ('neo', 'Neo'), ('minimal', 'Minimal')],
                    default='classic',
                    max_length=20,
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='preferences',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
    ]