# Generated by Django 5.2.15

from django.db import migrations

def reset_ratings(apps, schema_editor):
    PlayerRating = apps.get_model('game', 'PlayerRating')
    # Reset all ratings to 1200
    PlayerRating.objects.all().update(rating=1200)

def reverse_reset(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_userprogress_day_streak_and_more'),
    ]

    operations = [
        migrations.RunPython(reset_ratings, reverse_reset),
    ]
