# Generated by Django 6.0.5 on 2026-07-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_alter_chesspuzzle_rating_alter_chesspuzzle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('puzzles', 'Puzzles'), ('openings', 'Openings'), ('feedback', 'Feedback')], db_index=True, default='general', max_length=20),
        ),
    ]
