# Generated by Django 6.0.5 on 2026-07-25 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_discussion_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discussion',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('category__in', [
                        'general', 'puzzles', 'openings', 'feedback'
                    ])
                ),
                name='valid_discussion_category'
            ),
        ),
    ]
