# Generated by Django 6.0.5 on 2026-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_discussion_valid_discussion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='pgn',
            field=models.TextField(blank=True, default=''),
        ),
    ]
